algoritmo "varrecadado"
// Função : Calcular o valor arrecadado com a entrada de homens e mulheres em uma festa
// Autor : Luis Felipe
// Data : 13/03/2017
// Seção de Declarações 
var

h: inteiro
m: inteiro
valor: inteiro

inicio

escreva("Digite quantos homens foram a festa: ")
leia(h)
escreva("Digite quantas mulheres foram a festa: ")
leia(m)
valor <- (20 * h)+(17 * m)
escreva("O valor arrecadado foi de R$", valor)

fimalgoritmo
