algoritmo "nomes"
// Função : Mostra "Que nome bonito" se o nome digitado for Heitor, Cícero ou Pratico.
// Autor : Luis Felipe
// Data : 27/03/2017
// Seção de Declarações 
var

nome: caractere

inicio
escreva("Digite seu nome:")
leia(nome)

se (nome = "Heitor") ou (nome = "Cícero") ou (nome = "Prático") entao

   escreva("Que nome bonito")

senao

   escreva("Seu nome é ", nome)
   
fimse

fimalgoritmo
