algoritmo "triangulo"
// Função : Fazer o programa que digite três lados de um triângulo e mostra se forma um triângulo
// Autor : Luis Felipe
// Data : 27/03/2017
// Seção de Declarações 
var

n1, n2, n3: inteiro

inicio
escreva("Digite o primeiro lado: ")
leia(n1)
escreva("Digite o segundo lado: ")
leia(n2)
escreva("Digite o terceiro lado: ")
leia(n3)

se (n1 > (n2 - n3)) e (n1 < (n2 + n3)) entao

   escreva("Forma um triangulo")

fimse

fimalgoritmo
